services:
  web:
    env_file:
      - path: .env
        required: false
      - path: .env.local
        required: false
    build:
      context: .
      args:
        NEXT_PUBLIC_TTS_TEXT_LIMIT: ${NEXT_PUBLIC_TTS_TEXT_LIMIT:-5000}
    ports:
      - "3000:3000"
    environment:
      API_URL: ${API_URL:-http://host.docker.internal:8000}
      DOWNLOAD_FLAG: ${DOWNLOAD_FLAG:-true}
